theme: jekyll-theme-hacker
page_excerpts: true
title: Latest All Address Wallet
description: Latest Wallet Address and Balance with sorrted Rich Address Bitcoin Wallet and ethereum , litecoin, dogecoin , tron wallet and ...
# baseurl: "/Rich-Address-Wallet"
url: "https://pymmdrza.github.io/Rich-Address-Wallet"
plugins:
  - jekyll-remote-theme
# url create page from title
permalink: /:categories/:title/

# content section [pages / posts / products]
include:
  - pages
  - _includes
  - _layouts

navigation:
  - title: "Home"
    url: "/"
  - title: "Release"
    url: "https://github.com/Pymmdrza/Rich-Address-Wallet/releases"
  - title: "Latest Bitcoin Address"
    url: "https://github.com/Pymmdrza/Rich-Address-Wallet/releases/Latest.Bitcoin"
  - title: "Contact"
    url: "/pages/contact_page/"


